GET http://localhost:3000/health HTTP/1.1


###

POST http://localhost:3000/product HTTP/1.1
Content-Type: application/json

{
  "id": "d243zsvvqdZd0mTd",
  "title": "Galletas",
  "description": "Galletas Ricas de la abuela",
  "price": 100,
  "imageUrl": ["https://via.placeholder.com/150"]
}
